import React,{useState} from "react";
import toast from "react-hot-toast";
import jsPDF from "jspdf";
import {useCart} from "../context/CartContext";
import {useOrder} from "../context/OrderContext";

function validCard(n){return n.replace(/\D/g,"").length===16}
function validExpiry(v){return /^(0[1-9]|1[0-2])\/\d{2}$/.test(v)}
export default function CheckoutModal({open,onClose,onPlaced}){
 const {cart,total,clear}=useCart();const {place}=useOrder();
 const [form,setForm]=useState({name:"",phone:"",address:"",payment:"UPI / Razorpay (demo)",card:"",expiry:"",cvv:""});
 const [loading,setLoading]=useState(false);
 const update=e=>setForm({...form,[e.target.name]:e.target.value});
 const submit=async e=>{e.preventDefault();if(form.payment.includes("Card")&&(!validCard(form.card)||!validExpiry(form.expiry)||!/^\d{3}$/.test(form.cvv))){toast.error("Please enter valid demo card details");return}setLoading(true);await new Promise(r=>setTimeout(r,1200));const data={...form,total,items:cart.map(({id,name,price,qty})=>({id,name,price,qty}))};place(data);clear();setLoading(false);toast.success("Payment authorized • Order confirmed");generateInvoice(data);onClose();onPlaced()};
 const generateInvoice=data=>{const doc=new jsPDF();doc.setFontSize(22);doc.text("FoodRush Pro",20,25);doc.setFontSize(12);doc.text("Order Invoice",20,34);doc.text(`Customer: ${data.name}`,20,48);doc.text(`Phone: ${data.phone}`,20,56);doc.text(`Address: ${data.address}`,20,64);let y=80;data.items.forEach(i=>{doc.text(`${i.name} x ${i.qty}  ₹${i.price*i.qty}`,20,y);y+=8});doc.line(20,y,190,y);doc.text(`Total: ₹${data.total}`,20,y+10);doc.text("Payment: Demo authorization",20,y+18);doc.save("FoodRush-Invoice.pdf")};
 if(!open)return null;
 return <div className="modal-backdrop-custom"><div className="modal-card checkout-modal"><button className="modal-x" onClick={onClose}>×</button><span className="eyebrow">SECURE CHECKOUT</span><h3 className="fw-bold">Complete your order</h3><p className="text-secondary">Demo payment flow with client-side validation and invoice generation.</p><form onSubmit={submit}><div className="row g-3"><div className="col-md-6"><label>Name<input className="form-control" name="name" required value={form.name} onChange={update}/></label></div><div className="col-md-6"><label>Phone<input className="form-control" name="phone" required pattern="[0-9+ ]{10,15}" value={form.phone} onChange={update}/></label></div><div className="col-12"><label>Delivery address<textarea className="form-control" name="address" required value={form.address} onChange={update}/></label></div><div className="col-md-6"><label>Payment<select className="form-select" name="payment" value={form.payment} onChange={update}><option>UPI / Razorpay (demo)</option><option>Card / Stripe (demo)</option><option>Cash on delivery (demo)</option></select></label></div>{form.payment.includes("Card")&&<><div className="col-12 card-preview">💳 <span>FOODRUSH DEMO CARD</span><strong>{form.card||"•••• •••• •••• ••••"}</strong><small>{form.expiry||"MM/YY"} &nbsp; CVV {form.cvv?"•••":"•••"}</small></div><div className="col-md-6"><label>Card number<input className="form-control" name="card" inputMode="numeric" maxLength="16" placeholder="16 digits" value={form.card} onChange={update}/></label></div><div className="col-md-3"><label>Expiry<input className="form-control" name="expiry" placeholder="MM/YY" maxLength="5" value={form.expiry} onChange={update}/></label></div><div className="col-md-3"><label>CVV<input className="form-control" name="cvv" maxLength="3" value={form.cvv} onChange={update}/></label></div></>}<div className="col-12"><div className="checkout-total"><span>Total</span><strong>₹{total.toLocaleString("en-IN")}</strong></div></div><div className="col-12"><button className="btn btn-primary w-100 py-3" disabled={loading}>{loading?<><span className="spinner-border spinner-border-sm me-2"></span>Authorizing payment…</>:`Place order • ₹${total}`}</button></div></div></form></div></div>
}