import React,{useEffect,useRef,useState} from "react";
import L from "leaflet";
import {useOrder} from "../context/OrderContext";
import toast from "react-hot-toast";
export default function Tracking(){
 const {order}=useOrder();const mapRef=useRef(null);const map=useRef(null);const driver=useRef(null);const user=useRef(null);const line=useRef(null);const timer=useRef(null);
 const [loc,setLoc]=useState({lat:12.9716,lng:77.5946});const [status,setStatus]=useState(order?.status||"Ready to track");const [eta,setEta]=useState(order?"18–25 min":"Place an order first");
 useEffect(()=>{map.current=L.map(mapRef.current).setView([loc.lat,loc.lng],13);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"}).addTo(map.current);user.current=L.marker([loc.lat,loc.lng]).addTo(map.current).bindPopup("📍 Delivery destination");driver.current=L.marker([loc.lat+.025,loc.lng-.03]).addTo(map.current).bindPopup("🚴 Delivery partner");line.current=L.polyline([driver.current.getLatLng(),[loc.lat,loc.lng]],{dashArray:"8 8"}).addTo(map.current);return()=>{clearInterval(timer.current);map.current?.remove()}},[]);
 useEffect(()=>{if(user.current){user.current.setLatLng([loc.lat,loc.lng]);line.current?.setLatLngs([driver.current.getLatLng(),[loc.lat,loc.lng]])}},[loc]);
 const detect=()=>{if(!navigator.geolocation){toast.error("Geolocation is not supported");return}toast("Requesting location…");navigator.geolocation.getCurrentPosition(p=>{const next={lat:p.coords.latitude,lng:p.coords.longitude};setLoc(next);map.current.setView([next.lat,next.lng],14);toast.success("Your location detected")},()=>toast.error("Location permission denied. Demo location retained."),{enableHighAccuracy:true,timeout:10000})};
 const simulate=()=>{if(!order){toast("Place an order first");return}clearInterval(timer.current);let p=driver.current.getLatLng(),target=L.latLng(loc.lat,loc.lng),n=0;setStatus("Preparing");timer.current=setInterval(()=>{n++;p=L.latLng(p.lat+(target.lat-p.lat)*.08,p.lng+(target.lng-p.lng)*.08);driver.current.setLatLng(p);line.current.setLatLngs([p,target]);if(n===8)setStatus("Out for Delivery");if(n>28){clearInterval(timer.current);setStatus("Delivered");setEta("Arrived");toast.success("Delivery completed")}else setEta(`${Math.max(2,18-Math.floor(n/2))} min remaining`)},1000)};
 return <section id="tracking" className="section-pad"><div className="section-heading"><div><span className="eyebrow">LIVE DELIVERY</span><h2>Track your order in real time</h2><p>Browser geolocation + Leaflet map + persistent order lifecycle simulator.</p></div><div className="d-flex gap-2 flex-wrap"><button className="btn btn-outline-secondary" onClick={detect}>📍 Detect my location</button><button className="btn btn-primary" onClick={simulate}>▶ Start live simulation</button></div></div><div className="row g-4"><div className="col-lg-8"><div ref={mapRef} className="map-box"></div></div><div className="col-lg-4"><div className="tracking-card"><span className="live-dot"></span><b>{status}</b><small className="text-secondary d-block mt-1">ETA: {eta}</small><div className="timeline mt-4">{["Pending","Preparing","Out for Delivery","Delivered"].map((s,i)=><div className={"timeline-item "+(["Pending","Preparing","Out for Delivery","Delivered"].indexOf(status)>=i?"done":"")} key={s}><span>{i<["Pending","Preparing","Out for Delivery","Delivered"].indexOf(status)+1?"✓":i+1}</span><div><b>{s}</b><small>{i===0?"Order received":i===1?"Restaurant is preparing":i===2?"Driver location is moving":"Enjoy your meal!"}</small></div></div>)}</div><div className="driver-box">🚴 <div><b>Alex • Delivery Partner</b><small>Verified • 4.9★</small></div></div></div></div></div></section>
}