import React,{useMemo,useState} from "react";
import toast from "react-hot-toast";
import Navbar from "./components/Navbar";
import FoodCard from "./components/FoodCard";
import CartDrawer from "./components/CartDrawer";
import CheckoutModal from "./components/CheckoutModal";
import Tracking from "./components/Tracking";
import Dashboard from "./components/Dashboard";
import CheckoutSummary from "./components/CheckoutSummary";
import {categories,foods,restaurants} from "./data";
import {useOrder} from "./context/OrderContext";

export default function App(){
 const [cartOpen,setCartOpen]=useState(false),[checkout,setCheckout]=useState(false),[query,setQuery]=useState(""),[cat,setCat]=useState("All"),[diet,setDiet]=useState("All"),[price,setPrice]=useState("All"),[sort,setSort]=useState("Popular");
 const {order}=useOrder();
 const list=useMemo(()=>{let x=foods.filter(f=>(f.name+" "+f.cat).toLowerCase().includes(query.toLowerCase()));if(cat!=="All")x=x.filter(f=>f.cat===cat);if(diet!=="All")x=x.filter(f=>f.diet===diet);if(price==="Low")x=x.filter(f=>f.price<250);if(price==="Mid")x=x.filter(f=>f.price>=250&&f.price<=450);if(price==="High")x=x.filter(f=>f.price>450);if(sort==="Rating")x.sort((a,b)=>b.rating-a.rating);if(sort==="Price low")x.sort((a,b)=>a.price-b.price);if(sort==="Price high")x.sort((a,b)=>b.price-a.price);return x},[query,cat,diet,price,sort]);
 return <><Navbar onCart={()=>setCartOpen(true)}/><main>
 <section id="home" className="hero"><div className="container hero-inner"><div className="row align-items-center g-5"><div className="col-lg-6"><span className="eyebrow">FAST • FRESH • LOCAL</span><h1>Good food.<br/><span>Good mood.</span></h1><p className="lead text-secondary">Discover local favorites, order in seconds and follow your delivery live from restaurant to doorstep.</p><div className="hero-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search pizza, burgers, biryani…"/><a href="#menu" className="btn btn-primary">Search</a></div><div className="stats"><div><b>500+</b><small>Restaurants</small></div><div><b>4.8★</b><small>Average rating</small></div><div><b>25 min</b><small>Avg. delivery</small></div></div></div><div className="col-lg-6"><div className="hero-image"><div className="hero-offer"><small>TODAY'S DEAL</small><strong>30% OFF</strong><span>First order above ₹499</span></div></div></div></div></div></section>
 <section className="section-pad"><div className="container"><div className="section-heading"><div><span className="eyebrow">EXPLORE</span><h2>What are you craving?</h2></div></div><div className="category-grid">{categories.map(c=><button key={c.name} onClick={()=>{setCat(c.name);location.hash="menu"}}><span>{c.icon}</span><b>{c.name}</b></button>)}</div></div></section>
 <section id="restaurants" className="section-pad bg-soft"><div className="container"><div className="section-heading"><div><span className="eyebrow">TOP PICKS</span><h2>Popular restaurants</h2></div></div><div className="row g-4">{restaurants.map(r=><div className="col-sm-6 col-lg-4 col-xl-2" key={r.id}><article className="restaurant-card"><img src={r.img} alt={r.name}/><div className="p-3"><h6 className="fw-bold">{r.name}</h6><small className="text-secondary">{r.cuisine}</small><div className="small mt-2"><span className="rating">★ {r.rating}</span> • {r.time}</div><small className="text-success fw-semibold">● {r.status}</small></div></article></div>)}</div></div></section>
 <section className="promo section-pad"><div className="container"><div className="promo-box"><div><span className="eyebrow">LIMITED TIME</span><h2>30% off your first bite.</h2><p>Use <b>FIRSTBITE</b> at checkout. Demo promotion.</p></div><a href="#menu" className="btn btn-light">Explore food →</a></div></div></section>
 <section id="menu" className="section-pad"><div className="container"><div className="section-heading"><div><span className="eyebrow">DISCOVER FOOD</span><h2>Featured menu</h2><p>Search, filter by diet/price and sort by rating or popularity.</p></div></div><div className="filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="🔎 Search food…"/><select value={cat} onChange={e=>setCat(e.target.value)}><option>All</option>{categories.map(c=><option key={c.name}>{c.name}</option>)}</select><select value={diet} onChange={e=>setDiet(e.target.value)}><option>All</option><option value="veg">veg</option><option value="nonveg">nonveg</option></select><select value={price} onChange={e=>setPrice(e.target.value)}><option>All</option><option>Low</option><option>Mid</option><option>High</option></select><select value={sort} onChange={e=>setSort(e.target.value)}><option>Popular</option><option>Rating</option><option>Price low</option><option>Price high</option></select></div><div className="row g-4">{list.map(f=><div className="col-md-6 col-lg-4" key={f.id}><FoodCard food={f}/></div>)}</div>{!list.length&&<div className="empty-state">No food matches your filters.</div>}</div></section>
 {order&&<CheckoutSummary/>}<Tracking/><Dashboard/>
 <section className="section-pad"><div className="container faq"><div><span className="eyebrow">SMART RECOMMENDATIONS</span><h2>AI-style food recommendations</h2><p className="text-secondary">The demo recommends popular and highly rated items based on the current catalog. Connect an AI API on the server for production recommendations.</p></div><div className="recommend-grid">{foods.slice().sort((a,b)=>b.rating-a.rating).slice(0,3).map(f=><div className="recommend" key={f.id}><img src={f.img}/><div><b>{f.name}</b><small>Highly rated • {f.rating}★</small></div></div>)}</div></div></section>
 </main><footer><div className="container"><div className="row g-4"><div className="col-lg-5"><h4>🍽️ FoodRush<span className="accent">Pro</span></h4><p>Professional academic food delivery platform demo.</p></div><div className="col"><b>Platform</b><a href="#restaurants">Restaurants</a><a href="#menu">Menu</a><a href="#tracking">Live tracking</a></div><div className="col"><b>Support</b><a href="#home">Help center</a><a href="#home">Contact</a><a href="#home">Privacy</a></div><div className="col"><b>Contact</b><p>hello@foodrush.demo</p><p>+91 98765 43210</p></div></div><hr/><small>© 2026 FoodRush Pro • Built with React, Bootstrap, Leaflet and LocalStorage. Photos: Unsplash.</small></div></footer>
 <CartDrawer open={cartOpen} onClose={()=>setCartOpen(false)} onCheckout={()=>{setCartOpen(false);setCheckout(true)}}/><CheckoutModal open={checkout} onClose={()=>setCheckout(false)} onPlaced={()=>{toast.success("Invoice downloaded");location.hash="tracking"}}/>
 </>}
